---
title: "Platové tabulky veřejné správy a státní služby"
output: 
  html_notebook: 
    code_folding: hide
---

```{r echo=F, warning=F}
library(ggplot2)
library(dplyr)
library(grid)
library(scales)
library(ggthemes)
library(ggiraph)

load("tabulky_jenurednici.Rda")
load("tabulky2015_vsechny.Rda")
```

# Všechny tabulky, 2015

```{r plot all tables}
ggplot(ttall, aes(years, value/1e3, colour=tridanum, group=tridanum)) +
  geom_step() +
  scale_y_continuous(labels=comma, limits=c(0,50)) +
  scale_colour_continuous(breaks=c(1,16)) +
  facet_wrap(~tablelong) +
  theme(strip.text=element_text(size=14),
        text=element_text(size=13)) +
  guides(color=guide_colourbar(ticks = F, nbin = 16))
```


# Úřednické tabulky, 2014-2016
```{r plot 2014-6}
ggplot(data = uredset, aes(x=years, y=value/1e3, colour = tridanum, group = grp)) +
  geom_step(aes(linetype = trida1az5)) +
  facet_wrap(~ tabulka) +
  scale_y_continuous(labels=comma, limits=c(0,60),
                     breaks = c(0,10,20,30,40,50,60)) +
  # scale_colour_gradient2_tableau(breaks=c(1,16)) +
  theme(strip.text=element_text(size=14),
        text=element_text(size=13)) +
  guides(color=guide_colourbar(ticks = F, nbin = 16)) +
  scale_linetype_manual(values = c("TRUE" = "dotted", "FALSE" = "solid"))
```


# How much pay progression is there in each grade in the three points in time?

```{r}
uredset %>%
  mutate(tridanum = as.factor(tridanum)) %>%
  group_by(tabulka, tridanum) %>%
  summarise(narust = max(value)/min(value)-1) %>%
  ggplot(aes(tridanum, narust, group = tabulka)) + geom_line() + facet_wrap(~ tabulka) +
  scale_y_continuous(labels = percent, limits = c(0,1)) +
  theme_hc()
```

# Rozdíly mezi platovými třídami

```{r}
uredset %>%
  filter(!trida1az5) %>%
  mutate(stupen = as.factor(years)) %>%
  group_by(tabulka, years) %>%
  summarise(rozdil = max(value)/min(value)-1) %>%
  ggplot(aes(years, rozdil, group = tabulka)) + geom_line() + facet_wrap(~ tabulka) +
  geom_point() +
  scale_y_continuous(labels = percent, limits = c(1,2.2)) +
  theme_hc()
```

